services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - mysql
      - ollama
  app:
    container_name: app
    build:
      context: ./src
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - 9000:9000
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    env_file:
      - path: ./src/.env
        required: true
    environment:
      - MYSQL_DATABASE=backend
      - MYSQL_ROOT_PASSWORD=Aa648213579
    volumes:
      - db-data:/var/lib/mysql
      
  phpmyadmin:
    image:  phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 3304:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  # Ollama
  ollama:
    container_name: ollama
    build: 
      args:
        - model=gemma2:27b
      context: ./ollama
      dockerfile: Dockerfile
    working_dir: /root/.ollama
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

volumes:
  db-data: ~