services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
  app:
    container_name: laravel_app
    build:
      context: ./src
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - 9000:9000
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    env_file:
      - ./src/.env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      
  phpmyadmin:
    image:  phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 3304:80
    depends_on:
      - db

volumes:
  db-data: ~
