version: '3.8'

services:
  app:
    build:
      context: ./src/Docker
      target: Dockerfile
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
    ports:
      - 9000:9000

  database:
    image: mysql:8.0
    ports:
      - 3305:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE} 
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      
  phpmyadmin:
    image:  phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 3304:80
    depends_on:
      - database

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports: 
      - 6379:6379
volumes:
  db-data: ~
